/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui4;

/**
 *
 * @author CLASSROOM01
 */
public class GuiFive extends java.awt.Frame {

    /**
     * Creates new form GuiFive
     */
    public GuiFive() {
        initComponents();
        setSize(500,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new java.awt.Label();
        t1 = new java.awt.TextField();
        b1 = new java.awt.Button();
        panel1 = new java.awt.Panel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        l1.setText("NAME");
        add(l1);
        l1.setBounds(90, 60, 95, 30);
        add(t1);
        t1.setBounds(210, 60, 130, 30);

        b1.setLabel("SAVE");
        add(b1);
        b1.setBounds(160, 150, 57, 24);

        button1.setLabel("button1");
        panel1.add(button1);

        button2.setLabel("button2");
        panel1.add(button2);

        button3.setLabel("button3");
        panel1.add(button3);

        add(panel1);
        panel1.setBounds(120, 240, 210, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiFive().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button b1;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Label l1;
    private java.awt.Panel panel1;
    private java.awt.TextField t1;
    // End of variables declaration//GEN-END:variables
}
